### ISSUE TITLE
 Android Bootcamp Project ToDo app- Ready for Review. 

### ISSUE THREAD

**Issue by drana** [drana/droid_todoApp#1]
![todoapp_readme](https://cloud.githubusercontent.com/assets/1727811/15635706/271bf60a-259b-11e6-9c36-a5525e180004.gif)
My app is complete, please review. /cc @codepathreview and @codepath

Also I have a question about this part when I click on an item to edit I am able to navigate to edit activity and get the string to edit but the keyboard doesn't show up until I click on edit box. I think I am not setting the focus correctly. Please advise. 

Thank you

@drana

**Comment by nesquena** [comment]
Dipen,

Looks good, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

The next step is to continue working on [extensions to your todo app](http://courses.codepath.com/snippets/intro_to_android/prework#heading-5-extending-your-todo) and to **schedule a short 10 minute phone conversation** with us. Navigate to [today's date and onward from there](https://calendar.google.com/calendar/selfsched?sstoken=UURvT01vbzBza1pnfGRlZmF1bHR8NzVjYzBkN2EyZTRiOGRmYjZlZjhmMjA2N2IyMGMwYWU) and choose an available 15-minute slot in the mornings or evenings. Let us know if none of those times work. 

With regards to extensions to implement, we are looking for developers with an interest in user experience and product development so be sure to focus on additional functional enhancements and/or improving the user interface of the app.

Once you select a slot, can you make sure to **include the best number** to reach you at to the invite? Look forward to chatting soon!

**Comment by nesquena** [comment]
> Also I have a question about this part when I click on an item to edit I am able to navigate to edit activity and get the string to edit but the keyboard doesn't show up until I click on edit box. I think I am not setting the focus correctly. Please advise.

See this [guide on the soft keyboard](http://guides.codepath.com/android/Working-with-the-Soft-Keyboard) and how to make it visible by default.

**Comment by drana** [comment]
My app is complete, please review. /cc @codepathreview and @codepath

Also I have a question about this part when I click on an item to edit I am able to navigate to edit activity and get the string to edit but the keyboard doesn't show up until I click on edit box. I think I am not setting the focus correctly. Please advise.

Thank you

@drana

**Comment by codepathreview** [comment]
Hello Dipen, 

Looks great, this exercise is intended in part to give you an introduction to the general rhythm of this course. The course is entirely project-based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer  learn the practical elements of Android development and best practices as quickly as possible. We also do a code review for each submitted project once the program begins.

Great to see you were able to complete a large number of extensions to your app already. Your project looks great. As you can probably tell, the extension tasks available on each project are the valuable learnings since they dive deeper into common real-world Android use cases. 

Be sure to take a look through our [organizing your source files guide](http://guides.codepath.com/android/Organizing-your-Source-Files#android-folder-structure) for tips on organizing your code as well.

Now that you've completed the pre-work, we'll be following up with you again shortly to outline the next steps in the admissions process. 
/cc @coderschoolreview
